### ISSUE TITLE
Surface was not configured?

### ISSUE THREAD

**Issue by Jebkel** [Loara228/deadlock-esp#10]
Привет, я плохо разбираюсь в rust, по этому создаю тикет, так как сам справиться не смог

Во первых я изменил в Cargo.toml
```
[dependencies.windows]
windows = "0.58.0"
```

на

```
[dependencies.windows]
version = "0.58.0"
```

так как была ошибка
```
Caused by:
  dependency (windows) specified without providing a local path, Git repository, version, or workspace dependency to use
```

И опустил версию с 0.58 на 0.57, так как в 0.58 версии было много ошибок:

```
error[E0308]: mismatched types
     --> src\memory\mod.rs:73:48
      |
73    | pub static mut PROCESS_HANDLE: HANDLE = HANDLE(0);
      |                                         ------ ^ expected `*mut c_void`, found `usize`
      |                                         |
      |                                         arguments to this struct are incorrect
      |
      = note: expected raw pointer `*mut c_void`
                        found type `usize`
note: tuple struct defined here
     --> C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.58.0\src\Windows\Win32\Foundation\mod.rs:10643:12
      |
10643 | pub struct HANDLE(pub *mut core::ffi::c_void);
      |            ^^^^^^
help: if you meant to create a null pointer, use `std::ptr::null_mut()`
      |
73    | pub static mut PROCESS_HANDLE: HANDLE = HANDLE(std::ptr::null_mut());
      |                                                ~~~~~~~~~~~~~~~~~~~~

error[E0308]: mismatched types
     --> src\drawing\overlay.rs:92:26
      |
92    |         self.hwnd = HWND(hwnd.unwrap().get());
      |                     ---- ^^^^^^^^^^^^^^^^^^^ expected `*mut c_void`, found `isize`
      |                     |
      |                     arguments to this struct are incorrect
      |
      = note: expected raw pointer `*mut c_void`
                        found type `isize`
note: tuple struct defined here
     --> C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.58.0\src\Windows\Win32\Foundation\mod.rs:10866:12
      |
10866 | pub struct HWND(pub *mut core::ffi::c_void);
      |            ^^^^

error[E0308]: mismatched types
    --> src\drawing\screen.rs:12:38
     |
12   |             GetMonitorInfoA(HMONITOR(PRIMARY_MONITOR as isize), &mut ipmi);
     |                             -------- ^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut c_void`, found `isize`
     |                             |
     |                             arguments to this struct are incorrect
     |
     = note: expected raw pointer `*mut c_void`
                       found type `isize`
note: tuple struct defined here
    --> C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.58.0\src\Windows\Win32\Graphics\Gdi\mod.rs:8710:12
     |
8710 | pub struct HMONITOR(pub *mut core::ffi::c_void);
     |            ^^^^^^^^
```

После этих манипуляция я смог выполнить cargo build --release

Но возникла другая проблема, при запуске exe выдаёт такой лог:
```
[2024-09-23T09:01:37Z INFO  deadlock] Running...
[2024-09-23T09:01:37Z INFO  deadlock::memory] Process found: HANDLE(1688)
[2024-09-23T09:01:37Z INFO  deadlock::memory] Client: MODULEINFO { lpBaseOfDll: 0x7ffb3bf10000, SizeOfImage: 37261312, EntryPoint: 0x7ffb3d33de80 }
[2024-09-23T09:01:37Z INFO  deadlock::memory] Initialized
[2024-09-23T09:01:37Z INFO  deadlock::drawing::screen] SM_CMONITORS: 2
[2024-09-23T09:01:37Z INFO  deadlock::drawing::screen] MONITORINFO: MONITORINFO { cbSize: 0, rcMonitor: RECT { left: 0, top: 0, right: 0, bottom: 0 }, rcWork: RECT { left: 0, top: 0, right: 0, bottom: 0 }, dwFlags: 0 }
[2024-09-23T09:01:37Z INFO  deadlock::drawing::overlay] Running native window...
https://github.com/loara228/deadlock-esp
[2024-09-23T09:01:37Z INFO  deadlock::drawing::overlay] Overlay window: HWND(4131422)
thread 'main' panicked at C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.20.1\src\backend\wgpu_core.rs:770:14:
Surface was not configured?
```

Вот полный бектрейс:
```
[2024-09-23T09:01:37Z INFO  deadlock] Running...
[2024-09-23T09:01:37Z INFO  deadlock::memory] Process found: HANDLE(1688)
[2024-09-23T09:01:37Z INFO  deadlock::memory] Client: MODULEINFO { lpBaseOfDll: 0x7ffb3bf10000, SizeOfImage: 37261312, EntryPoint: 0x7ffb3d33de80 }
[2024-09-23T09:01:37Z INFO  deadlock::memory] Initialized
[2024-09-23T09:01:37Z INFO  deadlock::drawing::screen] SM_CMONITORS: 2
[2024-09-23T09:01:37Z INFO  deadlock::drawing::screen] MONITORINFO: MONITORINFO { cbSize: 0, rcMonitor: RECT { left: 0, top: 0, right: 0, bottom: 0 }, rcWork: RECT { left: 0, top: 0, right: 0, bottom: 0 }, dwFlags: 0 }
[2024-09-23T09:01:37Z INFO  deadlock::drawing::overlay] Running native window...
https://github.com/loara228/deadlock-esp
[2024-09-23T09:01:37Z INFO  deadlock::drawing::overlay] Overlay window: HWND(4131422)
thread 'main' panicked at C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.20.1\src\backend\wgpu_core.rs:770:14:
Surface was not configured?
stack backtrace:
   0:     0x7ff7c9482e3d - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ff7c9482e3d - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7c9482e3d - std::sys::backtrace::_print_fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\sys\backtrace.rs:65
   3:     0x7ff7c9482e3d - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\sys\backtrace.rs:40
   4:     0x7ff7c94a2969 - core::fmt::rt::Argument::fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\fmt\rt.rs:173
   5:     0x7ff7c94a2969 - core::fmt::write
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\fmt\mod.rs:1182
   6:     0x7ff7c947f681 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\io\mod.rs:1827
   7:     0x7ff7c9484e67 - std::panicking::default_hook::closure$1
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:269
   8:     0x7ff7c9484a59 - std::panicking::default_hook
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:296
   9:     0x7ff7c94855a2 - std::panicking::rust_panic_with_hook
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:800
  10:     0x7ff7c94853e6 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:674
  11:     0x7ff7c94837af - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\sys\backtrace.rs:168
  12:     0x7ff7c9484fc6 - std::panicking::begin_panic_handler
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
  13:     0x7ff7c94e3154 - core::panicking::panic_fmt
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
  14:     0x7ff7c94e311c - core::panicking::panic_display
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:264
  15:     0x7ff7c94e311c - core::option::expect_failed
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\option.rs:2030
  16:     0x7ff7c901fb5f - <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::surface_get_current_texture::h8f1e5632761000f3
  17:     0x7ff7c9030a8d - <T as wgpu::context::DynContext>::surface_get_current_texture::h504bce094954e367
  18:     0x7ff7c8f2ee7f - wgpu::Surface::get_current_texture::h49bec9576268c21a
  19:     0x7ff7c8ee434b - egui_wgpu::winit::Painter::paint_and_update_textures::hd41c4d253d5d4783
  20:     0x7ff7c8e3bed4 - <eframe::native::wgpu_integration::WgpuWinitApp as eframe::native::winit_integration::WinitApp>::run_ui_and_paint::h4a503f858c06dbad
  21:     0x7ff7c8e4c1ef - winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}::hb58c6605249fcc27
  22:     0x7ff7c8e54ddf - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind::hb3fb38393013d37c
  23:     0x7ff7c8e55295 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::move_state_to::h844ffe2dc4c55a5f
  24:     0x7ff7c8e1965e - winit::platform_impl::platform::event_loop::EventLoop<T>::wait_and_dispatch_message::h31b96f5de85e0a56
  25:     0x7ff7c8e190e8 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::ha3cc50fbf7fb44cf
  26:     0x7ff7c8dedc4b - eframe::native::run::run_wgpu::h4b1a0ec985748300
  27:     0x7ff7c8df7033 - eframe::run_native::h6c343fbfb4399e83
  28:     0x7ff7c8cebcc4 - deadlock::drawing::overlay::run::h2f5ddcc469dff2b9
  29:     0x7ff7c8cd3690 - deadlock::drawing::windows::draw_windows::hffedc337e404ac77
  30:     0x7ff7c8ce55f6 - std::sys::backtrace::__rust_begin_short_backtrace::h00e17177c6051f45
  31:     0x7ff7c8ce9b6c - std::rt::lang_start::{{closure}}::h9fd10f72721fb531
  32:     0x7ff7c947a659 - std::rt::lang_start_internal::closure$2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
  33:     0x7ff7c947a659 - std::panicking::try::do_call
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:557
  34:     0x7ff7c947a659 - std::panicking::try
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:521
  35:     0x7ff7c947a659 - std::panic::catch_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panic.rs:350
  36:     0x7ff7c947a659 - std::rt::lang_start_internal
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\rt.rs:141
  37:     0x7ff7c8cd402c - main
  38:     0x7ff7c94aa840 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  39:     0x7ff7c94aa840 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  40:     0x7ffbed4e257d - BaseThreadInitThunk
  41:     0x7ffbee40af28 - RtlUserThreadStart
```

Подскажите, может в каком-то моменте я ошибся или сделал что то не так?
Запускаю на windows 11, устанавливал rust с офф сайта последней версии x64

**Comment by Loara228** [comment]
Ты все сделал правильно.
Ошибка в том, что я не конфигурировал оверлей под 2+ монитора. Не могу это исправить из-за отсутствия второго монитора. 

Смотри тут
https://github.com/Loara228/deadlock-esp/blob/master/src%2Fdrawing%2Fscreen.rs

**Comment by Loara228** [comment]
Самое странное, что у меня работает. Даже не знаю, от чего это зависит. Возможно чуть позже (сейчас занят другими делами), я попробую при инициализации вручную настроить параметры окна.

**Comment by yuzurushX** [comment]
> I tried with 1 monitor and stumbled upon a black screen bug, judging by [emilk / egui # 4467](https://github.com/emilk/egui/pull/4467) it has not yet been corrected 

I got black screen too, in 1 monitor setup

**Comment by Loara228** [comment]
@Jebkel, напиши мне в телеграмм @hellocsharp

**Comment by Loara228** [comment]
Today I will try to fix it

**Comment by abcde89525** [comment]
I got this warning when I was building.

`cargo build --release
   Compiling windows v0.57.0
   Compiling sysinfo v0.31.4
   Compiling deadlock v0.1.0 (E:\Downloads\DLsite\deadlock-esp)
warning: unused `BOOL` that must be used
  --> src\drawing\screen.rs:12:13
   |
12 |             GetMonitorInfoA(HMONITOR(PRIMARY_MONITOR as isize), &mut ipmi);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
   |
12 |             let _ = GetMonitorInfoA(HMONITOR(PRIMARY_MONITOR as isize), &mut ipmi);
   |             +++++++

warning: `deadlock` (bin "deadlock") generated 1 warning
    Finished `release` profile [optimized] target(s) in 30.31s`

Should I just ignore the warning that the return value of the function is not used?

**Comment by Loara228** [comment]
> I got this warning when I was building.
> 
> cargo build --release
> 
> Compiling windows v0.57.0 Compiling sysinfo v0.31.4 Compiling deadlock v0.1.0 (E:\Downloads\DLsite\deadlock-esp) warning: unused `BOOL` that must be used --> src\drawing\screen.rs:12:13 | 12 | GetMonitorInfoA(HMONITOR(PRIMARY_MONITOR as isize), &mut ipmi); | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | = note: `#[warn(unused_must_use)]` on by default help: use `let _ = ...` to ignore the resulting value | 12 | let _ = GetMonitorInfoA(HMONITOR(PRIMARY_MONITOR as isize), &mut ipmi); | +++++++
> 
> warning: `deadlock` (bin "deadlock") generated 1 warning Finished `release` profile [optimized] target(s) in 30.31s`
> 
> Should I just ignore the warning that the return value of the function is not used?

just ignore. By the way, do you have a problem with the black screen?

**Comment by abcde89525** [comment]
> 忽略它即可。順便問一下，你有黑屏的問題嗎？

Yeah, the black screen problem happened to me too, so I'm waiting for a solution lol.
I'm also having problems with the Russian part being garbled after the build.

**Comment by Loara228** [comment]
@abcde89525 , @Jebkel , @yuzurushX ,
try it:
1. 
![image](https://github.com/user-attachments/assets/82068997-02e3-4378-b890-4fc0243042ee)
2.
![image](https://github.com/user-attachments/assets/32eab653-54c0-49b2-94cf-f84dff3cc0a4)
3.
![image](https://github.com/user-attachments/assets/5f2fada5-b3b4-42f2-8375-b85a3d5f8e62)

**Comment by Nikitosshow** [comment]
The screen is black anyway

**Comment by yuzurushX** [comment]
> @abcde89525 , @Jebkel , @yuzurushX , try it: 1. ![image](https://private-user-images.githubusercontent.com/91653434/369922068-82068997-02e3-4378-b890-4fc0243042ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDQ4MDIsIm5iZiI6MTcyNzEwNDUwMiwicGF0aCI6Ii85MTY1MzQzNC8zNjk5MjIwNjgtODIwNjg5OTctMDJlMy00Mzc4LWI4OTAtNGZjMDI0MzA0MmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE1MTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNTdjNGRiNjVkNmQzYzBhMGFhZDlkMmFlZDcyYTJlY2JiYTM3YTg3Y2VkZDczYmQ4MzMzMDU0MWUwY2ZhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nMv86UNVFwDk4hM3MS30JpTXN54eEYXTpEgdt0LOisk) 2. ![image](https://private-user-images.githubusercontent.com/91653434/369922195-32eab653-54c0-49b2-94cf-f84dff3cc0a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDQ4MDIsIm5iZiI6MTcyNzEwNDUwMiwicGF0aCI6Ii85MTY1MzQzNC8zNjk5MjIxOTUtMzJlYWI2NTMtNTRjMC00OWIyLTk0Y2YtZjg0ZGZmM2NjMGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE1MTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2OWI1NTRkMjY2NDdkNWE4MjY5MzQ1ODQ5MWZlZjg1NWMyOWM3ODM5ZGI5NmFhYzA4MjRjZTEyOWUyMTg1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zk5XfjEcaDr7gL6k5c6amE9t54L2vLVXQf-EkcQ7TOk) 3. ![image](https://private-user-images.githubusercontent.com/91653434/369922443-5f2fada5-b3b4-42f2-8375-b85a3d5f8e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDQ4MDIsIm5iZiI6MTcyNzEwNDUwMiwicGF0aCI6Ii85MTY1MzQzNC8zNjk5MjI0NDMtNWYyZmFkYTUtYjNiNC00MmYyLTgzNzUtYjg1YTNkNWY4ZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE1MTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOTRjMmVjYjg3MGUzYjAyMWY2NmM3MDYzOTBkNTVkODBiZjEzOWQ1MzYwNzNlYzk4NDdkMWNmMDlkMzYxMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5EhNlOYGaeo2TiNYQRsZMeOJDogj9QDnUe2BXpZshU0)

![image](https://github.com/user-attachments/assets/53b875ad-4b48-44d8-b437-2b468721ef4b)
still persist
