### ISSUE TITLE
Фикс работает нооо....

### ISSUE THREAD

**Issue by Nikitosshow** [Loara228/deadlock-esp#12]
Вх поломалось, типо все ворк, но вх почему отдельно от модели: 
![image](https://github.com/user-attachments/assets/00d4878c-d6a2-438b-b07b-cc8001ea3f0d)
![image](https://github.com/user-attachments/assets/bfc37d04-8805-4090-bebc-4f0b330b84e3)
а радар норм работает

**Comment by Nikitosshow** [comment]
а еще конфиги крашат софт(

**Comment by Nikitosshow** [comment]
UPD: проблема только на ноуте, на пк все ок

**Comment by Nikitosshow** [comment]
фикс вышел

**Comment by Nikitosshow** [comment]
@Loara228 короче когда в винде стоит 125% экрана, то вх багается и слазит с героя, на 100% все ок

**Comment by Loara228** [comment]
@Nikitosshow, Краш загрузки файла конфигурации был связан с чем, что он пытался десериализировать прошлую [Settings](https://github.com/Loara228/deadlock-esp/blob/8e0189a9e126b954223f63222c48a16052106643/src/settings/structs.rs#L45) версию. Сейчас в таком случае загружается default актуальной структуры. 
Спасибки за инфу с масштабированием <3.
