### ISSUE TITLE
Wallhack don't work

### ISSUE THREAD

**Issue by edok3q** [Loara228/deadlock-esp#14]
Не работает вх, но работает радар

**Comment by Loara228** [comment]
[offsets](https://github.com/Loara228/deadlock-esp/blob/90c54b922ded3313164548863c10ed817ef6e3b8/src/external/offsets/mod.rs#L3).

**Comment by Jebkel** [comment]
@Indokq in src/external/offsets/mod.rs change offsets to
```
pub mod client {   
    pub const dwEntityList: usize = 0x1f24948;
    pub const dwViewMatrix: usize = 0x20e22d0;
    pub const dwLocalPlayerController: usize = 0x20d0668;
    pub const CCitadelCameraManager: usize = 0x1f46230;
}
```

**Comment by abcde89525** [comment]
> @Indokq在 src/external/offsets/mod.rs 中將偏移量改為
> 
> ```
> pub mod client {   
>     pub const dwEntityList: usize = 0x1f24948;
>     pub const dwViewMatrix: usize = 0x20e22d0;
>     pub const dwLocalPlayerController: usize = 0x20d0668;
>     pub const CCitadelCameraManager: usize = 0x1f46230;
> }
> ```

Hello, how should I obtain these offsets? If you can teach me, I would greatly appreciate it!

**Comment by Loara228** [comment]
https://github.com/Loara228/deadlock-esp/blob/old/scanner%2Fsrc%2Fmain.rs
