### ISSUE TITLE
 If the resolution is not 1080p, it will cause overlay rendering errors.

### ISSUE THREAD

**Issue by abcde89525** [Loara228/deadlock-esp#16]
![Uploading image.png…](https://media.discordapp.net/attachments/806894619282899004/1288191614321430528/image.png?ex=66f4496e&is=66f2f7ee&hm=ede0d9f7e35c0c3b1be90168dca5c202c328cd8b1da18984ab094a0ad6268dc9&=&format=webp&quality=lossless&width=550&height=309)

My screen is 1440p, which causes the overlay to display in the wrong position.

**Comment by Loara228** [comment]
Try to remove scaling in windows settings or program properties

**Comment by abcde89525** [comment]
Yes, I have referred to previous issue reports and also tried checking my scaling settings, but I'm using the default 100% without any changes (I’m use a desktop).

**Comment by abcde89525** [comment]
Actually, I suspect the issue lies with the version I compiled because it seems to include many new features that are not yet complete, resulting in numerous errors or warnings. I had to modify many parts in order to compile it successfully.

![image](https://media.discordapp.net/attachments/806894619282899004/1288203010568093758/image.png?ex=66f4540b&is=66f3028b&hm=39fae34a7df5902eca2075dfe97424359472bfb9df2f67b878f1bbcf18a7a37e&=&format=webp&quality=lossless&width=871&height=935)
![image](https://media.discordapp.net/attachments/806894619282899004/1288203011214151690/image.png?ex=66f4540b&is=66f3028b&hm=22a4afb7bd1cc4f118e6e207f9082273fee0fa86c34c49c41acbf7a9aabae4c1&=&format=webp&quality=lossless)

**Comment by abcde89525** [comment]
@Loara228  Hello, is there a way to control the render size manually?
I've found that in order to get the overlay to display in the correct position, I have to change the windows11 display scale to about 130%.

**Comment by Loara228** [comment]
Here you can specify your screen resolution

https://github.com/Loara228/deadlock-esp/blob/bd230ea6f7df5b44519669359b55d49d96f920e4/src/drawing/screen.rs#L5

```rs
    return (
        Vec2 { x: 0., y: 0. },
        Vec2 { x: 800f32, y: 600f32 }
    );
```

![image](https://github.com/user-attachments/assets/147dc261-83bd-44db-a12f-1ef4dfbdb3a3)

**Comment by abcde89525** [comment]
Cool,thanks!
