### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by 5k-omar** [Loara228/deadlock-esp#2]
internal static IntPtr dwEntityList = 0x23b5f78;
internal static IntPtr ViewMatrix = 0x2573e30;
internal static IntPtr LocalPlayerController = 0x2562300;
internal static IntPtr CCitadelCameraManager = 0x23d7960;
        
Can you create a tutorial explaining how to find these **offsets** myself, or give me a way to find them?

Because game update every sec

**Comment by Loara228** [comment]
dwEntityList: 48 8B 0D ? ? ? ? 8B C5 48 C1 E8
ViewMatrix: 48 8D 05 ? ? ? ? 48 03 C3
LocalPlayerController: 4C 8B 05 ? ? ? ? 8B D3 48 8B CD
CCameraManager: 48 8D 3D ? ? ? ? 8B D9 89 4C 24 48 8B 0D ? ? ? ? 41 B8 ? ? ? ?

**Comment by 5k-omar** [comment]
> dwEntityList: 48 8B 0D ? ? ? ? 8B C5 48 C1 E8 ViewMatrix: 48 8D 05 ? ? ? ? 48 03 C3 LocalPlayerController: 4C 8B 05 ? ? ? ? 8B D3 48 8B CD CCameraManager: 48 8D 3D ? ? ? ? 8B D9 89 4C 24 48 8B 0D ? ? ? ? 41 B8 ? ? ? ?

only dwEntityList  work

**Comment by Loara228** [comment]
After yesterday's update, the patterns are no longer available.
You can try this:
```cs
Console.WriteLine("local");
FindPattern("48 8B 0D ? ? ? ? 48 85 C9 74 65 83 FF FF");
Console.WriteLine("matrix");
FindPattern("48 8D 0D ? ? ? ? 48 C1 E0");
 ```
