### ISSUE TITLE
Just Information

### ISSUE THREAD

**Issue by darkvallen** [Loara228/deadlock-esp#24]
I just got banned and turned into a frog using this xD be careful out there, don't make it so obvious

**Comment by abcde89525** [comment]
frog?

**Comment by abcde89525** [comment]
@darkvallen Do you know which one is the aimbot trigger button?
(Is your aimbot working well?

**Comment by Nikitosshow** [comment]
@abcde89525 aim button: mouse 4 and mouse 5, for hero and creeps

**Comment by Loara228** [comment]
It's sad :(
I was lucky. I played 10+ games after the patch and everything is fine.

**Comment by darkvallen** [comment]
> @darkvallen Do you know which one is the aimbot trigger button? (Is your aimbot working well?

Super well, you could change the button settings on the config

**Comment by darkvallen** [comment]
> It's sad :( I was lucky. I played 10+ games after the patch and everything is fine.

i played 20+ games after the patch, I think don't play it too obvious

**Comment by Nikitosshow** [comment]
This is a console command, no need to listen to a pathetic frog, played more than 50 games

**Comment by Loara228** [comment]
@Nikitosshow, A lot of my friends play with software. It doesn't ban anyone. Maybe the author of the post was playing with another cheat?

**Comment by Nikitosshow** [comment]
maybe

**Comment by darkvallen** [comment]
> This is a console command, no need to listen to a pathetic frog, played more than 50 games

I swear i use this, i didnt have ang intention to discredit this, just sharing and increase awareness
