### ISSUE TITLE
Cheat need update

### ISSUE THREAD

**Issue by Adi2071** [Loara228/deadlock-esp#25]
I couldn't compile it at all. Problem with the Chinese language. I had to remove it and then I managed to compile it. Then it turned out that nothing in the game worked. Only the menu. I found a video to check the file.
https://www.youtube.com/watch?v=gnKinCZqeqk

It turns out that the offsets are incorrect.Please help.

![deadlock](https://github.com/user-attachments/assets/5712dc8c-1b9c-4563-8ea4-feb3678a30c4)

**Comment by Nikitosshow** [comment]
damn, you dont open game
@Adi2071

**Comment by Nikitosshow** [comment]
problem with compile because author dont connect ch lang

**Comment by Nikitosshow** [comment]
I think an update will be released soon

**Comment by Adi2071** [comment]
![image](https://github.com/user-attachments/assets/d2825960-7321-4d1e-86d6-5aa3abdfb671)

![image](https://github.com/user-attachments/assets/63235f48-c6cb-4ded-bdaa-f0f3131ae617)

The menu works but nothing else.

**Comment by Loara228** [comment]
Локализацию с китайским языком исправил.

@Adi2071, На счет "WARN Unknown hero index: 0" это нормально. Такое бывает, когда указатель игрока в памяти существует, а его данные еще не загрузились. Прости что на русском пишу, мне лень открывать переводчик

**Comment by Nikitosshow** [comment]
@Loara228 будешь сегодня грузить еще обновы? Легенда, скок ПТС в доте и добавь в Тодо бинд аима)

**Comment by abcde89525** [comment]
> I couldn't compile it at all. Problem with the Chinese language. I had to remove it and then I managed to compile it. Then it turned out that nothing in the game worked. Only the menu. I found a video to check the file. https://www.youtube.com/watch?v=gnKinCZqeqk
> 
> It turns out that the offsets are incorrect.Please help.
> 
> ![deadlock](https://private-user-images.githubusercontent.com/13559370/372954581-5712dc8c-1b9c-4563-8ea4-feb3678a30c4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODkwMTEsIm5iZiI6MTcyNzg4ODcxMSwicGF0aCI6Ii8xMzU1OTM3MC8zNzI5NTQ1ODEtNTcxMmRjOGMtMWI5Yy00NTYzLThlYTQtZmViMzY3OGEzMGM0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE3MDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZWQxODc4NTVkM2IzMDViOGQ2OTk0OGM5YmM4Y2RkNjdjMThkNTZjODFkOGJiMTE4OTA1ZjUwOWIxZTBmMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5TPIsoqUXI6DVEs9_CcgFoZfdw_a-MkkI2WsFAMFf1I)

Missing Chinese character files when building
Create assets\fonts folder in the project root directory.
Download open source fonts. https://github.com/ButTaiwan/iansui
Change the file name to Iansui.ttf.

**Comment by Adi2071** [comment]
@Loara228 

Без проблем. Хотелось бы узнать, почему у меня ничего в игре не работает? Возможно, его действительно необходимо обновить и перекомпилировать.

**Comment by Nikitosshow** [comment]
и на русском как то так себе смотрится шрифт

**Comment by Nikitosshow** [comment]
@Adi2071, нужно обновить оффсеты в файле, или же запускать cmd и писать deadlock -o, тогда оффсеты будут искаться из памяти

**Comment by Loara228** [comment]
> и на русском как то так себе смотрится шрифт
@Nikitosshow, исправил. Забыл убрать метод для смены шрифта на китайский.
@Adi2071, Try to repeat the first step (The game should be open.). https://github.com/Loara228/deadlock-esp/issues/18

**Comment by Adi2071** [comment]
@Loara228 

Не могли бы вы прислать готовые, обновленные файлы? Мои весят 300-400 кб, а подписи из темы №18 отличаются от таковых из дампера.

**Comment by Adi2071** [comment]
@Loara228 
Последняя версия работает отлично. У меня к вам просьба. Вы бы добавили гуманизацию?
https://www.unknowncheats.me/forum/valorant/561583-zier-curves-mouse-movement-humanization.html


Вы можете установить режим аимбота стандартным и очеловечить его в настройках. Это должно сделать аимбота менее искусственным и незаметным.

**Comment by 874091376** [comment]
The game has updated the ranking mode, cheating does not work

**Comment by Loara228** [comment]
@874091376, yep, big update
![image](https://github.com/user-attachments/assets/914c0d8b-5434-4ff9-943e-e35bde83729c)
![image](https://github.com/user-attachments/assets/ed96f28a-6784-461d-a92a-e1d4e98e159e)

**Comment by 874091376** [comment]
> @874091376, yep, big update ![image](https://private-user-images.githubusercontent.com/91653434/375645458-914c0d8b-5434-4ff9-943e-e35bde83729c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzUxMDIsIm5iZiI6MTcyODYzNDgwMiwicGF0aCI6Ii85MTY1MzQzNC8zNzU2NDU0NTgtOTE0YzBkOGItNTQzNC00ZmY5LTk0M2UtZTM1YmRlODM3MjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4MjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMzVkOWMwNDgwOWY1MzhkNmY4YTI4OWRhZGRlZjlmMTY1ZjhkYjAyOGI2YjVjZWE4ZDZmYjc2M2NjM2I3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lDNY4lfwkJ2zbsmG83YZdoa8x99mDThtoRd8CCgBdkw) ![image](https://private-user-images.githubusercontent.com/91653434/375645465-ed96f28a-6784-461d-a92a-e1d4e98e159e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzUxMDIsIm5iZiI6MTcyODYzNDgwMiwicGF0aCI6Ii85MTY1MzQzNC8zNzU2NDU0NjUtZWQ5NmYyOGEtNjc4NC00NjFkLWE5MmEtZTFkNGU5OGUxNTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4MjAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMDkxM2QyZDE1YzkyZWIzMzE3Y2I5OWY5Y2VmMDNkNzQ1ZmQxNDg2N2Q3ZTU0ZDMwNzZhMDJhZDZjODhmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7-E29SXbmoW0k417ZOhws7TrXPrTyq7YKl5VyjnOhzs)

Thank you
