### ISSUE TITLE
Из-за чего лягушка

### ISSUE THREAD

**Issue by Nikitosshow** [Loara228/deadlock-esp#27]
@Loara228, я прочитал из-за чего бывает лягушка, короче когда тип стреляет 40+ пуль онли в голову, то тогда анти чит палит, так что надо делать распределение урона по остальным частям тела, или сделать функцию типо когда включаешь ее, то аим пытается распределить урон😏

**Comment by Loara228** [comment]
Тебя забанили?) Откуда узнал?

**Comment by Nikitosshow** [comment]
Амбрелла брат)

**Comment by Nikitosshow** [comment]
Ну опять же, я не утверждаю, потому что скатав уже 60+ игр бана нет, может опять же как в доте обычная волна

**Comment by Loara228** [comment]
@Nikitosshow, Нет, волн тут нету. Знакомый словил лягушку (ХАХАХА, звучит ахуенно) недавно со своим личным читом.

**Comment by Nikitosshow** [comment]
Ну значит они рил нашли из-за чего, ну рил, теперь вместо банов лягушка)

**Comment by Nikitosshow** [comment]
Сейчас занимаешься чем то из списка?)

**Comment by Loara228** [comment]
Не. вообще ничего не делаю.

**Comment by Nikitosshow** [comment]
Я кстати у себя сделал чтоб прога запускалась сразу с поиском ассетов, по моему удобно

**Comment by Jebkel** [comment]
@Nikitosshow Античит не палит(по крайней мере то, что просто попадаешь постоянно в голову), как по мне это исключительно ручные баны, которые приходят специально во время игр, что бы хомячки посмеялись над лягухой

**Comment by Loara228** [comment]
@Jebkel, мб детекст на голову есть, а потом анализ данных. Ни один человек не может в такой динамичной игре стрелять только в голову всю игру)

**Comment by Loara228** [comment]
Я, скорее всего, не буду ничего делать для распределения стрельбы.. Я играю только на пакете и у себя сделал чтобы стрельба была только в тело или шею. Думаю после 4-го акта в доте вообще перестану обновлять репозиторий. (Зависит от обновы)
![maxresdefault](https://github.com/user-attachments/assets/7bb03076-6f70-46a0-bb61-5d89bc1487ac)

**Comment by Nikitosshow** [comment]
Сделай авто пари, 😞 @Loara228

**Comment by Loara228** [comment]
> Сделай авто парирование,😞 @Loara228

Когда я что-то делаю челы на UC просто выкладывают мой код от своего имени.  Думаю в этот раз я просто подожду, когда они опубликуют чей-то еще код. Не хочу тратить время на пендосов

**Comment by Nikitosshow** [comment]
Понял, ну скинь мне просто в телеге, я тебе спасибо скажу и легенда😉

**Comment by darkvallen** [comment]
Finally you guys trusted me right, i don't lie @Nikitosshow

**Comment by Nikitosshow** [comment]
@darkvallen, I do not know how you played that you were banned, I have played at the moment 5 pages of games and I was not banned, I saw this news in the sources

**Comment by Nikitosshow** [comment]
@Loara228 а где ты добавил аим на другие частит тела?)

**Comment by Loara228** [comment]
@Nikitosshow, Воть сюда))
Но пока не выложил 
![image](https://github.com/user-attachments/assets/4df41682-2b97-46cc-9b1a-ae8a1f6dd07b)

**Comment by Nikitosshow** [comment]
Понял)ждем

**Comment by Loara228** [comment]
Чесн говоря я уже 3+ часа просто играю. Мне тупо правку сделать небольшую и можно выкладывать. Но мне лень. Сейчас я уже пишу не для людей, а для себя и кореша

**Comment by Nikitosshow** [comment]
Понятно, ну я буду все равно ждать 😉

**Comment by Loara228** [comment]
@Nikitosshow, Если ты чисто поиграть хочешь, то выложил релиз билд. Исходник не буду выкладывать.
Только на английский не переключайся, а то я чисто случайно вместе него китайский поставил))))))))0)

**Comment by Nikitosshow** [comment]
> @Nikitosshow, Если ты чисто поиграть хочешь, то выложил релиз билд. Исходник не буду выкладывать. Только на английский не переключайся, а то я чисто случайно вместе него китайский поставил))))))))0)

Понял, ну я поиграю, а так печально(

**Comment by Loara228** [comment]
[Английская локализация](https://www.youtube.com/watch?v=9i7sX6O__t0).
