### ISSUE TITLE
Пофиксишь сигнатуры?

### ISSUE THREAD

**Issue by Nikitosshow** [Loara228/deadlock-esp#29]
Сегодня ночью патч вышел и сигнатуры поломались @Loara228 😌

**Comment by Nikitosshow** [comment]
И как их вообще ищешь?

**Comment by Loara228** [comment]
@Nikitosshow, сигнатуры в порядке. Всю ночь играл.

**Comment by Nikitosshow** [comment]
не робит( 
![image](https://github.com/user-attachments/assets/7465c8e1-955d-4c97-9dc9-a8d0d579410a)

**Comment by Nikitosshow** [comment]
[2024-10-11T08:08:55Z WARN  eblan666::external::interfaces::enums] unknown hero id: 1073741824
[2024-10-11T08:08:55Z WARN  eblan666::external::interfaces::structs] Unknown hero index: 1073741824
А раньше вообще другое писало

**Comment by Loara228** [comment]
@Nikitosshow, смещения структур обновились. Я потом залью
![Screenshot 2024-10-11 111632](https://github.com/user-attachments/assets/7d8fcec6-f21c-419e-9176-2e3e41f83b83)

**Comment by Nikitosshow** [comment]
@Loara228 окей, спасибо

**Comment by Loara228** [comment]
Они и так работают

**Comment by Nikitosshow** [comment]
я тупой, все понял)

**Comment by Loara228** [comment]
https://github.com/Loara228/deadlock-esp/blob/master/src/external/offsets/mod.rs
