### ISSUE TITLE
вопросы по оффсетам

### ISSUE THREAD

**Issue by Kramar1337** [Loara228/deadlock-esp#3]
ку
такой вопрос
как получить
m_pGameSceneNode = 0x328;
m_ihealth = 0x790 + 16;
m_iMaxHealth = 0x758 + 16;
в [source2gen](https://github.com/neverlosecc/source2gen) отличаются
у челов на форуме UC тоже другие
как найти правильные оффсеты?
зачем "0x790 + 16" почему не записать целиком "0x7A0"?

**Comment by Loara228** [comment]
1. Как получить? Самый легкий способ — просто на форуме брать.
2. Почему отличаются? В s2gen офсет от Pawn игрока. У меня другой, который идет от Controller.
3. Как найти правильные офсеты? Дампер. Ну и тот же ответ в первом вопросе. Только нужно проверять актуальность.
4. Зачем «+16»? После обновления изменилась структура, и я просто добавил к старым указателям смещение (в 16 байт), которое указывает на актуальные данные.
4.1 Можно было и просто написать 0x7A0, но это что-то из разряда [магических чисел](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)).
