### ISSUE TITLE
Cheat cannot be used normally

### ISSUE THREAD

**Issue by Gragle526** [Loara228/deadlock-esp#30]
![屏幕截图 2024-10-11 171941](https://github.com/user-attachments/assets/e7c213c7-027e-43de-a5ae-6e0922bf2dde)
Yesterday I was able to play with the plugin normally. After today's update I compiled with Cargo again and turned on the plugin and found that Aim and ESP were not working. In addition, I can not use the command in step 4 in Powershell properly. Yesterday and today, I opened the application in./targets/release/ directly

**Comment by Gragle526** [comment]
![image](https://github.com/user-attachments/assets/c54fe9ad-9fd7-4689-90ac-d9fddedf4aa6)

**Comment by Loara228** [comment]
@Gragle526, Offsets outdated. 

I will post new ones later

dumper: https://github.com/a2x/cs2-dumper
changes: https://github.com/Loara228/deadlock-esp/issues/18#issuecomment-2407021336

**Comment by Gragle526** [comment]
thank you

**Comment by seablue-233** [comment]
Thank you very much to the Loara228. I tried to update it myself, but my ability is not enough

**Comment by Loara228** [comment]
updated
https://github.com/Loara228/deadlock-esp/blob/master/src/external/offsets/mod.rs
