### ISSUE TITLE
Here is one bug after update

### ISSUE THREAD

**Issue by Gragle526** [Loara228/deadlock-esp#33]
![image](https://github.com/user-attachments/assets/16565f95-0fd7-4a4c-a1a9-a33fdde9eedd)

**Comment by daybeforethesuicide** [comment]
Дополню, крашит при игре на шиве, вернее после каждой его смерти эта же ошибка как на скрине + ошибка в коде хиро скрипты, и чит выключается, все пропадает, и консоль просто висит.

**Comment by Loara228** [comment]
fixed
