### ISSUE TITLE
Автоматическая функция скрипта не работает, а интерфейс меню сценариев пуст!

### ISSUE THREAD

**Issue by 874091376** [Loara228/deadlock-esp#36]
Автоматическая функция скрипта не работает, а интерфейс меню сценариев пуст!

**Comment by Nikitosshow** [comment]
Какая автоматическая функция?

**Comment by Nikitosshow** [comment]
Скрипты (Не выложил. Хочу еще добавить парочку и потестить)
Скрипт на заточку
Скрипт на пуджа
Возможность добавить свои скрипты
Пример бинда настройки через скрипт на вкл/выкл ESP
Прочие мелочи

**Comment by Loara228** [comment]
@874091376, Hi. I have published only the basic interface for creating scripts. I stopped posting updates for a while. There are no special reasons for this. It's just that I'm writing the project only for myself and friends.
