### ISSUE TITLE
Аим

### ISSUE THREAD

**Issue by Jebkel** [Loara228/deadlock-esp#4]
Будете ли вы добавлять аим?
Я пытался на основе вашего кода и кода от cs2 добавить топорный аим на основе движения мыши, но заткнулся на моменте, когда не смог получить m_vecAbsOrigin

И ещё вопрос, почему пропал радар?

**Comment by Loara228** [comment]
Вероятно, в будущем я займусь созданием чита и добавлю в них функции (например, тот же аим), но не в ближайшее время.
Радар мне не подошёл, поэтому я решил его убрать. Позже я обдумаю его работу и сделаю более удобным.
