### ISSUE TITLE
choosing english in the menu seem to still be russian

### ISSUE THREAD

**Issue by tinywifi** [Loara228/deadlock-esp#46]
choosing english in the menu seem to still be russian

**Comment by seablue-233** [comment]
![11111111](https://github.com/user-attachments/assets/919bbd46-fd4d-4153-adec-89b67a28b083)

![image](https://github.com/user-attachments/assets/76974273-fc04-4096-bd35-5e123d3fb810)

src\drawing\windows.rs
Just modify it

**Comment by Loara228** [comment]
ctor:
https://github.com/Loara228/deadlock-esp/blob/6ce6ff7d31dec17403dfa9a9fa6052d109389fc7/src/drawing/overlay.rs#L123
