### ISSUE TITLE
Игра обновляется! Обман не сработал.

### ISSUE THREAD

**Issue by 874091376** [Loara228/deadlock-esp#47]
Игра обновляется! Обман не сработал.

**Comment by Loara228** [comment]
https://github.com/Loara228/deadlock-esp/issues/18#issuecomment-2431413636

**Comment by 874091376** [comment]
Спасибо за все!

**Comment by 874091376** [comment]
> [#18（评论）](https://github.com/Loara228/deadlock-esp/issues/18#issuecomment-2431413636)

Закончил обновление?

**Comment by Nikitosshow** [comment]
> > [#18（评论）](https://github.com/Loara228/deadlock-esp/issues/18#issuecomment-2431413636)
> 
> Закончил обновление?

it will no longer support development!

**Comment by Loara228** [comment]
Updated. You can download the build here: https://github.com/Loara228/deadlock-esp/releases/tag/release
