### ISSUE TITLE
external::interfaces::structs] Unknown hero index: 1073741824

### ISSUE THREAD

**Issue by nanashi1116** [Loara228/deadlock-esp#48]
Can you help me with this?
![123](https://github.com/user-attachments/assets/c01af1a0-87b7-424e-8fcf-503a35287aea)

**Comment by tinywifi** [comment]
game updated

**Comment by Loara228** [comment]
Updated. You can download the build here: https://github.com/Loara228/deadlock-esp/releases/tag/release
