### ISSUE TITLE
Добавишь сохранение скрипов?

### ISSUE THREAD

**Issue by Nikitosshow** [Loara228/deadlock-esp#49]
Привет, @Loara228 добавишь сохранение скриптов в конфиг?

**Comment by Nikitosshow** [comment]
и где вот это взять) 
![image](https://github.com/user-attachments/assets/27514c32-a0fa-44c1-af2e-09c8df5d66a1)
а то я так понимаю это у тебя в файле dev.rs?

**Comment by Nikitosshow** [comment]
и можно ли как то сделать визибл чек?

**Comment by Loara228** [comment]
1. добавлю сохранение скриптов.
2. cl_showpos 1 (команда из движка игры)
3. в теории да, в моем проекте нет.
