### ISSUE TITLE
bDormant, перезарядка, парирование

### ISSUE THREAD

**Issue by Kramar1337** [Loara228/deadlock-esp#51]
привет. 
делаю самодельный чит, такой вопрос

как в чит энжине найти состояние жив - мертв?
Использую анализ структур в CE и иду по:
C_CitadelPlayerPawn + m_pGameSceneNode(0x330) + m_bDormant(0xef) = а тут пусто
Работает на душах, на персонажах нет
CCitadelPlayerController + m_pGameSceneNode(0x330) + m_bDormant(0xef) = ?
из всего что нашел(m_lifeState, m_bAlive, m_ihealth) только m_bDormant работает корректно, но не могу его применить.

вопрос 2
как посчитать перезарядку ультимейта?
есть
CCitadelPlayerController + offsets.m_PlayerDataGlobal + offsets.m_flUltimateCooldownStart
CCitadelPlayerController + offsets.m_PlayerDataGlobal + offsets.m_flUltimateCooldownEnd
но не знаю где взять время матча
искал тут:
client.dll + dwGlobalVars(0x1EE6970)
client.dll + dwGameRules(0x222B188)
и там и там время сервера а время матча нету(не нашел)

вопрос 3
как сделать парирование?
перебрать игроков, посчитать расстояние, если нажат спел то нажать "F"
по идее легко, но есть нюанс
где в памяти искать "холд тычку"?

**Comment by Loara228** [comment]
Привет, 
1. Использую это. Работает корректно

```rs
pub fn is_invalid(&self) -> bool
{
self.controller.ptr as usize == 0
}
pub fn is_alive(&self) -> bool
{
self.data.alive && self.pawn.health > 0 // m_bAlivePlayerDataGlobal_t::m_bAlive
}
```

2. Осталось = m_flUltimateCooldownEnd -  Время игры + время паузы
3. Примерно вот так: перебрать игроков, посчитать расстояние, если нажат спел то нажать "F"

Я не искал способ сделать авто парирование. Сейчас я не делаю ничего серьезного.

**Comment by Kramar1337** [comment]
понял. спасибо
