### ISSUE TITLE
Вопрос по поводу андетекта

### ISSUE THREAD

**Issue by erxson** [Loara228/deadlock-esp#53]
Я дилетант в этих ваших хакингах и киберпреступлениях, поэтому у меня возник вопрос.

Античиту VAC совсем похер на OpenProcess PROCESS_QUERY_INFORMATION | PROCESS_VM_READ и ReadProcessMemory или у тебя настолько большой член, что это тебе совсем похер на этот нищий VAC и в целом на этот грязный запад?

Ну я там попытался почитать че-то да на всяких ункновнчеатс.ме (киберхакергигамега сайт ну шарим да в теме йоу), но шота ребята ничего внятного и точного так и не написали, кроме "не будь балбесом и тебя не задетектят".

**Comment by Loara228** [comment]
Здарова. Если кратко, то да. Им похер, йоу

![image](https://github.com/user-attachments/assets/4dba323c-40dc-49b2-a9f1-95fd1c68fbdf)

Если немного углубиться, то тяжело понять, что именно делает программа с твоим хендлом. Можно узнать, если кто-то имеет хендл твоей программы. Можно узнать, если используется extern метод RPM. Но доказать это, не копаясь лично с бинарником, сложно. Это может быть антивирус или индусская программа для RGB-подсветки окна)))

Вот еще пример нескольких методов, которые используют хендл из .NET фреймворка.

![image](https://github.com/user-attachments/assets/e8ccae17-3906-417b-ba42-e8a974b7f530)

_не обфусцируй меня пж_

**Comment by erxson** [comment]
> Но доказать это, не копаясь лично с бинарником, сложно. Это может быть антивирус или индусская программа для RGB-подсветки окна)))
аххх как же прогрели этих гоев
Спасибо за ответ! 💋

**Comment by Loara228** [comment]
<h1>💪стая блох💪</h1>
