### ISSUE TITLE
К большому сожалению игру обновили ! Милорд, моих сил и знаний недостаточно что бы обновить сие чудо. Прошу у вас помощи, ну или совета что делать.

### ISSUE THREAD

**Issue by setikus** [Loara228/deadlock-esp#58]

**Comment by Loara228** [comment]
Не гоже крестьянину молвить о делах не сельских.

Да воздаст тебе хранитель комитов информацию об агнеце, что бросил чуждое ему дело. Упаси тебя господь.

PS: Я уже не играю в дедлок. Делал проект в первую очередь для себя. Обновления не поанирую.

**Comment by setikus** [comment]
Анлак=( Ну а мини гайдик ? хотя бы как смещения обновить ?) Я слишком слаб в этом деле.
