### ISSUE TITLE
Ещё раз для глупых

### ISSUE THREAD

**Issue by mcgeorge2k** [Loara228/deadlock-esp#65]
Не могу собрать файл, ругается на ошибки, уже весь интернет перерыл но решения не могу найти. Можно пожалуйста линк на готовый .exe файлик?)

**Comment by y0shih** [comment]
https://cdn.discordapp.com/attachments/1284734634004844584/1314728175812476999/app123.exe?ex=67557c47&is=67542ac7&hm=08915faba8f5b1cbef05b5aaab46732d4d14d7aacb80a59dd8d280d5e2398abf&

**Comment by Loara228** [comment]
Мне лень компилировать

**Comment by mcgeorge2k** [comment]
> https://cdn.discordapp.com/attachments/1284734634004844584/1314728175812476999/app123.exe?ex=67557c47&is=67542ac7&hm=08915faba8f5b1cbef05b5aaab46732d4d14d7aacb80a59dd8d280d5e2398abf&

"This content is no longer available." при переходе по ссылке:(
