### ISSUE TITLE
Проблема при использовании

### ISSUE THREAD

**Issue by Nikitosshow** [Loara228/deadlock-esp#9]
Такая проблема что я запускаю программу, но вх просто сверху всех приложений, ни свернуть ничего, просто черный экран и вх
![image](https://github.com/user-attachments/assets/ede65360-cb30-4121-acd3-e3eb9590ffac)
![image](https://github.com/user-attachments/assets/910b311b-8893-42f7-9e44-6706d8ae2e31)

**Comment by Nikitosshow** [comment]
на кнопку закрытия меню нажимал

**Comment by Loara228** [comment]
попробуй это
https://github.com/Loara228/deadlock-esp/issues/10#issuecomment-2368470591

**Comment by Loara228** [comment]
[fixed](https://github.com/Loara228/deadlock-esp/commit/82e38be9afa025622bc02c2588c04fcaaaa79661#diff-f5ed05d9d48445344db44518e394ee5b5b4e5f85481a34473294e24df00a2282R18)

**Comment by Rempacious** [comment]
По-прежнему черный экран
